//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BudgetData()
        {
            this.BudgetDivide = new HashSet<BudgetDivide>();
        }
    
        public int ID { get; set; }
        public int BudgetID { get; set; }
        public int MonthID { get; set; }
        public decimal MoneyPlanOPH { get; set; }
        public decimal MoneyPlanFRP { get; set; }
        public decimal MoneyOutlayOPH { get; set; }
        public decimal MoneyOutlayFRP { get; set; }
        public decimal MoneyFactOther { get; set; }
        public decimal MoneySumOutlayOPH { get; set; }
        public decimal MoneySumOutlayFRP { get; set; }
        public Nullable<int> ImportFileBudgetDataID { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual ImportFileBudgetData ImportFileBudgetData { get; set; }
        public virtual Month Month { get; set; }
        public virtual Version Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetDivide> BudgetDivide { get; set; }
    }
}
