//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetCompensation
    {
        public int ID { get; set; }
        public int MonthID { get; set; }
        public int DistributorID { get; set; }
        public decimal Value { get; set; }
        public decimal CoInvTotal { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Month Month { get; set; }
    }
}
