//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetListingOutlayView
    {
        public int RegionASMID { get; set; }
        public int DistributorID { get; set; }
        public int InvestTitleID { get; set; }
        public int MonthID { get; set; }
        public Nullable<decimal> Outlay { get; set; }
        public int ContractID { get; set; }
        public Nullable<int> PaymentRequestID { get; set; }
    }
}
