//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetDivide
    {
        public int ID { get; set; }
        public int BudgetDataID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal MoneyOPH { get; set; }
        public decimal MoneyFRP { get; set; }
        public decimal MoneySum { get; set; }
        public string Comment { get; set; }
    
        public virtual BudgetData BudgetData { get; set; }
    }
}
