//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractMatchingCache
    {
        [Key, ForeignKey("Contract")]
        public int ContractID { get; set; }
        public bool IsAuthorized { get; set; }
        public Nullable<bool> HasApprovedWithInTime { get; set; }
        public Nullable<bool> HasMatchPaymentTerm { get; set; }
        public Nullable<bool> HasMatchInvestmentDirection { get; set; }
        public Nullable<bool> HasMatchPaymentMethod { get; set; }
        public decimal InvestPercentFact { get; set; }
        public decimal InvestPercentPlan { get; set; }
        public Nullable<bool> HasMatchConditions { get; set; }
        public Nullable<bool> HasMatchInvestmentPercent { get; set; }
        public System.DateTime LastChangeDateTime { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
