//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractConditionPlan
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int ConditionID { get; set; }
        public decimal Value { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
