//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatusHistory
    {
        public int ID { get; set; }
        public int ContractId { get; set; }
        public Nullable<int> ContractStatusIdOld { get; set; }
        public int ContractStatusIdNew { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> CreationUserId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ApprovementState { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ContractStatus ContractStatus { get; set; }
        public virtual ContractStatus ContractStatus1 { get; set; }
        public virtual User User { get; set; }
    }
}
