//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractMonthConditionMatchingView
    {
        public int ContractID { get; set; }
        public int MonthID { get; set; }
        public int IsVisible { get; set; }
        public Nullable<bool> HasMatchConditions { get; set; }
        public Nullable<bool> IsCurrentMonth { get; set; }
    }
}
