//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractFilterView
    {
        public int QUserID { get; set; }
        public int QUserRoleID { get; set; }
        public int QUserRegionID { get; set; }
        public int ContractID { get; set; }
        public int ContractStatusID { get; set; }
        public int DistributorID { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int CreationUserID { get; set; }
        public int IsTradeNet { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsAuthorized { get; set; }
        public Nullable<int> SalePointID { get; set; }
        public Nullable<int> TradeNetID { get; set; }
        public string Name { get; set; }
        public int RegionID { get; set; }
        public Nullable<decimal> InvestmentPercent { get; set; }
        public int PaymentTermID { get; set; }
        public int PaymentMethodID { get; set; }
        public int InvestDirectionID { get; set; }
        public int InvestSubjectID { get; set; }
        public string InvestSubjectName { get; set; }
    }
}
