//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractMonthConditionMatchingCache
    {
        [Key, Column(Order=0)]
        public int ContractID { get; set; }
        [Key, Column(Order=1)]
        public int MonthID { get; set; }
        public Nullable<bool> HasMatchConditions { get; set; }
        public bool IsCurrentMonth { get; set; }
        public System.DateTime LastChangeDateTime { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Month Month { get; set; }
    }
}
