//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoleVisibility
    {
        public int ID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ContractStatusID { get; set; }
        public Nullable<int> ApprovementStateID { get; set; }
        public Nullable<bool> MustBeOwner { get; set; }
    
        public virtual ContractStatus ContractStatus { get; set; }
        public virtual Role Role { get; set; }
    }
}
