//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTotalOutlay
    {
        public int ContractID { get; set; }
        public decimal TotalOutlaySum { get; set; }
        public System.DateTime LastChangedateTime { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
