//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFileBudgetData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportFileBudgetData()
        {
            this.BudgetData = new HashSet<BudgetData>();
        }
    
        public int ID { get; set; }
        public int ImportFileBudgetID { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string DistributorName { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public string ASMRegionName { get; set; }
        public Nullable<int> ASMRegionID { get; set; }
        public string InvestAnalyticTitleName { get; set; }
        public Nullable<decimal> BudgetOPHYear { get; set; }
        public Nullable<decimal> BudgetOPHJan { get; set; }
        public Nullable<decimal> BudgetOPHFeb { get; set; }
        public Nullable<decimal> BudgetOPHMar { get; set; }
        public Nullable<decimal> BudgetOPHApr { get; set; }
        public Nullable<decimal> BudgetOPHMay { get; set; }
        public Nullable<decimal> BudgetOPHJun { get; set; }
        public Nullable<decimal> BudgetOPHJul { get; set; }
        public Nullable<decimal> BudgetOPHAug { get; set; }
        public Nullable<decimal> BudgetOPHSep { get; set; }
        public Nullable<decimal> BudgetOPHOct { get; set; }
        public Nullable<decimal> BudgetOPHNov { get; set; }
        public Nullable<decimal> BudgetOPHDec { get; set; }
        public Nullable<decimal> OutlayOPHYear { get; set; }
        public Nullable<decimal> OutlayOPHRemains { get; set; }
        public Nullable<decimal> OutlayOPHBalance { get; set; }
        public Nullable<decimal> OutlayOPHJan { get; set; }
        public Nullable<decimal> OutlayOPHFeb { get; set; }
        public Nullable<decimal> OutlayOPHMar { get; set; }
        public Nullable<decimal> OutlayOPHApr { get; set; }
        public Nullable<decimal> OutlayOPHMay { get; set; }
        public Nullable<decimal> OutlayOPHJun { get; set; }
        public Nullable<decimal> OutlayOPHJul { get; set; }
        public Nullable<decimal> OutlayOPHAug { get; set; }
        public Nullable<decimal> OutlayOPHSep { get; set; }
        public Nullable<decimal> OutlayOPHOct { get; set; }
        public Nullable<decimal> OutlayOPHNov { get; set; }
        public Nullable<decimal> OutlayOPHDec { get; set; }
        public Nullable<decimal> BudgetFRPYear { get; set; }
        public Nullable<decimal> BudgetFRPJan { get; set; }
        public Nullable<decimal> BudgetFRPFeb { get; set; }
        public Nullable<decimal> BudgetFRPMar { get; set; }
        public Nullable<decimal> BudgetFRPApr { get; set; }
        public Nullable<decimal> BudgetFRPMay { get; set; }
        public Nullable<decimal> BudgetFRPJun { get; set; }
        public Nullable<decimal> BudgetFRPJul { get; set; }
        public Nullable<decimal> BudgetFRPAug { get; set; }
        public Nullable<decimal> BudgetFRPSep { get; set; }
        public Nullable<decimal> BudgetFRPOct { get; set; }
        public Nullable<decimal> BudgetFRPNov { get; set; }
        public Nullable<decimal> BudgetFRPDec { get; set; }
        public Nullable<decimal> OutlayFRPYear { get; set; }
        public Nullable<decimal> OutlayFRPRemains { get; set; }
        public Nullable<decimal> OutlayFRPBalance { get; set; }
        public Nullable<decimal> OutlayFRPJan { get; set; }
        public Nullable<decimal> OutlayFRPFeb { get; set; }
        public Nullable<decimal> OutlayFRPMar { get; set; }
        public Nullable<decimal> OutlayFRPApr { get; set; }
        public Nullable<decimal> OutlayFRPMay { get; set; }
        public Nullable<decimal> OutlayFRPJun { get; set; }
        public Nullable<decimal> OutlayFRPJul { get; set; }
        public Nullable<decimal> OutlayFRPAug { get; set; }
        public Nullable<decimal> OutlayFRPSep { get; set; }
        public Nullable<decimal> OutlayFRPOct { get; set; }
        public Nullable<decimal> OutlayFRPNov { get; set; }
        public Nullable<decimal> OutlayFRPDec { get; set; }
        public Nullable<decimal> BudgetSumYear { get; set; }
        public Nullable<decimal> BudgetSumJan { get; set; }
        public Nullable<decimal> BudgetSumFeb { get; set; }
        public Nullable<decimal> BudgetSumMar { get; set; }
        public Nullable<decimal> BudgetSumApr { get; set; }
        public Nullable<decimal> BudgetSumMay { get; set; }
        public Nullable<decimal> BudgetSumJun { get; set; }
        public Nullable<decimal> BudgetSumJul { get; set; }
        public Nullable<decimal> BudgetSumAug { get; set; }
        public Nullable<decimal> BudgetSumSep { get; set; }
        public Nullable<decimal> BudgetSumOct { get; set; }
        public Nullable<decimal> BudgetSumNov { get; set; }
        public Nullable<decimal> BudgetSumDec { get; set; }
        public Nullable<decimal> OutlaySumYear { get; set; }
        public Nullable<decimal> OutlaySumRemains { get; set; }
        public Nullable<decimal> OutlaySumBalance { get; set; }
        public Nullable<decimal> OutlaySumJan { get; set; }
        public Nullable<decimal> OutlaySumFeb { get; set; }
        public Nullable<decimal> OutlaySumMar { get; set; }
        public Nullable<decimal> OutlaySumApr { get; set; }
        public Nullable<decimal> OutlaySumMay { get; set; }
        public Nullable<decimal> OutlaySumJun { get; set; }
        public Nullable<decimal> OutlaySumJul { get; set; }
        public Nullable<decimal> OutlaySumAug { get; set; }
        public Nullable<decimal> OutlaySumSep { get; set; }
        public Nullable<decimal> OutlaySumOct { get; set; }
        public Nullable<decimal> OutlaySumNov { get; set; }
        public Nullable<decimal> OutlaySumDec { get; set; }
        public Nullable<decimal> PaymentYear { get; set; }
        public Nullable<decimal> PaymentJan { get; set; }
        public Nullable<decimal> PaymentFeb { get; set; }
        public Nullable<decimal> PaymentMar { get; set; }
        public Nullable<decimal> PaymentApr { get; set; }
        public Nullable<decimal> PaymentMay { get; set; }
        public Nullable<decimal> PaymentJun { get; set; }
        public Nullable<decimal> PaymentJul { get; set; }
        public Nullable<decimal> PaymentAug { get; set; }
        public Nullable<decimal> PaymentSep { get; set; }
        public Nullable<decimal> PaymentOct { get; set; }
        public Nullable<decimal> PaymentNov { get; set; }
        public Nullable<decimal> PaymentDec { get; set; }
        public Nullable<decimal> Remain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetData> BudgetData { get; set; }
    }
}
