//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportContract
    {
        public int ID { get; set; }
        public string Дистрибьютор { get; set; }
        public string ASM { get; set; }
        public string SRM { get; set; }
        public string SR { get; set; }
        public string Город_область { get; set; }
        public string Территория_ { get; set; }
        public string Сегмент__ТТ_сети_ { get; set; }
        public Nullable<double> ID__TT { get; set; }
        public string ID_сети { get; set; }
        public string Юрид__Лицо__ТТ_сети_ { get; set; }
        public string Фактический_адрес__для_ТТ_ { get; set; }
        public string Канал__для_ТТ_ { get; set; }
        public string Категория__для_ТТ_ { get; set; }
        public string Кол_во_ТТ__для_сети_ { get; set; }
        public string Условия_оплаты_ { get; set; }
        public string Форма_оплаты { get; set; }
        public string ретро_бонус__процент { get; set; }
        public string Предмет_инвестирования { get; set; }
        public string Направление_инвестирования { get; set; }
        public Nullable<double> SKU2014 { get; set; }
        public Nullable<double> SKU2015 { get; set; }
        public Nullable<double> Shelve2014 { get; set; }
        public Nullable<double> Shelve2015 { get; set; }
        public Nullable<double> HO2014 { get; set; }
        public Nullable<double> HO2015 { get; set; }
        public Nullable<double> HOConcurr2014 { get; set; }
        public Nullable<double> HOConcurr2015 { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<double> Инвест_нат_SKU__ID_Jeans__ { get; set; }
        public string Инвест_нат_Наименование_SKU { get; set; }
        public Nullable<double> Инвест_нат_факт_2014__в_рамках_текущего_контракта_ { get; set; }
        public Nullable<double> Инвест_нат_янв { get; set; }
        public Nullable<double> Инвест_нат_фев { get; set; }
        public Nullable<double> Инвест_нат_март { get; set; }
        public Nullable<double> Инвест_нат_апр { get; set; }
        public Nullable<double> Инвест_нат_май { get; set; }
        public Nullable<double> Инвест_нат_июнь { get; set; }
        public Nullable<double> Инвест_нат_июль { get; set; }
        public Nullable<double> Инвест_нат_авг { get; set; }
        public Nullable<double> Инвест_нат_сент { get; set; }
        public Nullable<double> Инвест_нат_окт { get; set; }
        public Nullable<double> Инвест_нат_ноя { get; set; }
        public Nullable<double> Инвест_нат_дек { get; set; }
        public Nullable<double> Инвест_нат_план_2016__в_рамках_текущего_контракта_ { get; set; }
        public Nullable<double> Инвест_нат_Итого_в_рамках_контракта_ { get; set; }
        public Nullable<double> Инвест_руб_факт_2014_ { get; set; }
        public Nullable<double> Инвест_руб_янв { get; set; }
        public Nullable<double> Инвест_руб_фев { get; set; }
        public Nullable<double> Инвест_руб_март { get; set; }
        public Nullable<double> Инвест_руб_апр { get; set; }
        public Nullable<double> Инвест_руб_май { get; set; }
        public Nullable<double> Инвест_руб_июнь { get; set; }
        public Nullable<double> Инвест_руб_июль { get; set; }
        public Nullable<double> Инвест_руб_авг { get; set; }
        public Nullable<double> Инвест_руб_сент { get; set; }
        public Nullable<double> Инвест_руб_окт { get; set; }
        public Nullable<double> Инвест_руб_ноя { get; set; }
        public Nullable<double> Инвест_руб_дек { get; set; }
        public Nullable<double> Инвест_руб_план_2016 { get; set; }
        public Nullable<double> Инвест_руб_Итого_контракта_ { get; set; }
        public Nullable<double> Продажи_руб_2014_ { get; set; }
        public Nullable<double> Продажи_руб_янв { get; set; }
        public Nullable<double> Продажи_руб_фев { get; set; }
        public Nullable<double> Продажи_руб_март { get; set; }
        public Nullable<double> Продажи_руб_апр { get; set; }
        public Nullable<double> Продажи_руб_май { get; set; }
        public Nullable<double> Продажи_руб_июнь { get; set; }
        public Nullable<double> Продажи_руб_июль { get; set; }
        public Nullable<double> Продажи_руб_авг { get; set; }
        public Nullable<double> Продажи_руб_сент { get; set; }
        public Nullable<double> Продажи_руб_окт { get; set; }
        public Nullable<double> Продажи_руб_ноя { get; set; }
        public Nullable<double> Продажи_руб_дек { get; set; }
        public Nullable<double> Продажи_руб_2016 { get; set; }
        public Nullable<double> Среднемесячные_продажи_ТТ__РУБЛИ { get; set; }
        public Nullable<double> Период_контракта__кол_во_мес { get; set; }
        public Nullable<double> Кол_во_записей_по_ТТ { get; set; }
        public Nullable<System.DateTime> Дата_мин { get; set; }
        public Nullable<System.DateTime> Дата_макс { get; set; }
        public Nullable<double> Суммарный_период_инвест_я { get; set; }
        public Nullable<double> Расчетные_продажи_в_период_инвестирования__РУБЛИ { get; set; }
        public Nullable<double> Общие_инвестиции__РУБЛИ { get; set; }
        public Nullable<double> C__инвестирования { get; set; }
        public string Статус { get; set; }
        public Nullable<double> Месяц_внесения_или_обновления_записи { get; set; }
        public Nullable<double> Последний_месяц_обновления { get; set; }
        public string Закр_док_ты_янв { get; set; }
        public string Закр_док_ты_фев { get; set; }
        public string Закр_док_ты_март { get; set; }
        public string Закр_док_ты_апр { get; set; }
        public string Закр_док_ты_май { get; set; }
        public string Закр_док_ты_июнь { get; set; }
        public string Закр_док_ты_июль { get; set; }
        public string Закр_док_ты_авг { get; set; }
        public string Закр_док_ты_сент { get; set; }
        public string Закр_док_ты_окт { get; set; }
        public string Закр_док_ты_ноя { get; set; }
        public string Закр_док_ты_дек { get; set; }
        public string ФИО_отвественного_со_стороны_ТТ_сети { get; set; }
        public string Тел_ответ_го_со_стороны_ТТ_сети { get; set; }
        public string Комментарии { get; set; }
        public Nullable<int> Load { get; set; }
    }
}
