//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFileBudget
    {
        public int ID { get; set; }
        public int VersionID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreationUserID { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual User User { get; set; }
        public virtual Version Version { get; set; }
    }
}
