//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestStandartImport
    {
        public int ID { get; set; }
        public string Регион { get; set; }
        public string Город__справочно__не_для_заливки_ { get; set; }
        public string ASM_ФИО { get; set; }
        public string ASM_ID { get; set; }
        public string SRM_ФИО { get; set; }
        public string SRM_ID { get; set; }
        public string Канал { get; set; }
        public string Сети_Розница { get; set; }
        public string Предмет_инвестирования { get; set; }
        public Nullable<double> MAX____инвестирования_ { get; set; }
        public string ХОЛОДИЛЬНИК_Установка_нового_ХО_ { get; set; }
        public string ХОЛОДИЛЬНИК_Удержание__текущего_ХО_ { get; set; }
        public string ХОЛОДИЛЬНИК_Перемещение_ХО_на_лучшее_место { get; set; }
        public string ХОЛОДИЛЬНИК_Размещение_нашей_продукции_в_ХО_клиента { get; set; }
        public string АССОРТИМЕНТ_Построение_дистрибьюции_ { get; set; }
        public string АССОРТИМЕНТ_Построение_дистрибьюции_TOP_SKU_ { get; set; }
        public string АССОРТИМЕНТ_Поддержание_ассортимента { get; set; }
        public string Полка { get; set; }
        public string Пакет { get; set; }
        public string ПРОЧEE_ДМП { get; set; }
        public string ПРОЧEE_Ретро_бонус_за_объем { get; set; }
        public string ПРОЧEE_Уникальный_партнер_ { get; set; }
        public string ПРОЧEE_Брендинг { get; set; }
        public string ПРОЧEE_TPR { get; set; }
        public string C_НАПРАВЛЕНИЯ_ИНВЕСТИРОВАНИЯ { get; set; }
    }
}
