//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestStandartPercent
    {
        public int ID { get; set; }
        public int RegionID { get; set; }
        public Nullable<bool> IsTradeNet { get; set; }
        public int SalePointChannelID { get; set; }
        public int InvestSubjectID { get; set; }
        public decimal MaxInvestPercent { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual InvestSubject InvestSubject { get; set; }
        public virtual Region Region { get; set; }
        public virtual SalePointChannel SalePointChannel { get; set; }
    }
}
