//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvestTitle()
        {
            this.Budget = new HashSet<Budget>();
            this.InvestSubject = new HashSet<InvestSubject>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string KeyName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool CanUserAddDirection { get; set; }
        public bool CanUserEditBudgetOutlay { get; set; }
        public bool CanUserEditBudgetFactOther { get; set; }
        public bool CanUserEditBudgetFactCompensation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestSubject> InvestSubject { get; set; }
    }
}
