//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestPercentPlanView
    {
        public int ContractID { get; set; }
        public decimal InvestPercentFact { get; set; }
        public decimal InvestPercentPlan { get; set; }
        public Nullable<bool> HasMatchInvestmentPercent { get; set; }
    }
}
