//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Month()
        {
            this.BudgetCompensation = new HashSet<BudgetCompensation>();
            this.BudgetData = new HashSet<BudgetData>();
            this.ConditionFact = new HashSet<ConditionFact>();
            this.ContractMonth = new HashSet<ContractMonth>();
            this.ContractMonthConditionMatchingCache = new HashSet<ContractMonthConditionMatchingCache>();
            this.InvestPercentFact = new HashSet<InvestPercentFact>();
            this.SellOut = new HashSet<SellOut>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime ActualDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ActualYear { get; set; }
        public Nullable<int> ActualMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetCompensation> BudgetCompensation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetData> BudgetData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConditionFact> ConditionFact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractMonth> ContractMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractMonthConditionMatchingCache> ContractMonthConditionMatchingCache { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestPercentFact> InvestPercentFact { get; set; }
        public virtual Version Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellOut> SellOut { get; set; }
    }
}
