//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int PaymentRequestID { get; set; }
        public decimal Value { get; set; }
        public Nullable<int> SkuId { get; set; }
        public Nullable<decimal> SkuQuantity { get; set; }
        public Nullable<System.DateTime> LastChangeDateTime { get; set; }
        public Nullable<int> LastChangeUserID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int PaymentMethodID { get; set; }
        public int CreationUserID { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual Sku Sku { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
