//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequestStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequestStatus()
        {
            this.PaymentRequest = new HashSet<PaymentRequest>();
            this.PaymentRequestStatusActionMap = new HashSet<PaymentRequestStatusActionMap>();
            this.PaymentRequestStatusActionMap1 = new HashSet<PaymentRequestStatusActionMap>();
            this.PaymentRequestStatusHistory = new HashSet<PaymentRequestStatusHistory>();
            this.PaymentRequestStatusHistory1 = new HashSet<PaymentRequestStatusHistory>();
            this.PaymentRequestSectionMap = new HashSet<PaymentRequestSectionMap>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool AllowMultiple { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusActionMap> PaymentRequestStatusActionMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusActionMap> PaymentRequestStatusActionMap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusHistory> PaymentRequestStatusHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusHistory> PaymentRequestStatusHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestSectionMap> PaymentRequestSectionMap { get; set; }
    }
}
