//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequest()
        {
            this.Payment = new HashSet<Payment>();
            this.PaymentRequestStatusHistory = new HashSet<PaymentRequestStatusHistory>();
        }
    
        public int ID { get; set; }
        public int PaymentPlanID { get; set; }
        public int PaymentRequestTypeID { get; set; }
        public int PaymentRequestStatusID { get; set; }
        public System.DateTime PaymenRequestDate { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int CreationUserID { get; set; }
        public decimal Value { get; set; }
        public Nullable<int> SkuId { get; set; }
        public Nullable<decimal> SkuQuantity { get; set; }
        public Nullable<System.DateTime> LastChangeDateTime { get; set; }
        public Nullable<int> LastChangeUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual PaymentPlan PaymentPlan { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus { get; set; }
        public virtual PaymentRequestType PaymentRequestType { get; set; }
        public virtual Sku Sku { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusHistory> PaymentRequestStatusHistory { get; set; }
    }
}
