//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequestStatusActionMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequestStatusActionMap()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public int SourceID { get; set; }
        public int TargetID { get; set; }
        public int ActionID { get; set; }
        public int OrderInList { get; set; }
    
        public virtual PaymentRequestStatus PaymentRequestStatus { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus1 { get; set; }
        public virtual PaymentRequestStatusAction PaymentRequestStatusAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
    }
}
