//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlanRealView
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int ContractStatusID { get; set; }
        public int MonthID { get; set; }
        public int ContractorID { get; set; }
        public int PaymentPlanID { get; set; }
        public decimal PaymentPlanValue { get; set; }
        public Nullable<int> PaymentPlanSkuID { get; set; }
        public Nullable<decimal> PaymentPlanSkuQuantity { get; set; }
        public Nullable<int> ActualYear { get; set; }
    }
}
