//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentPlan()
        {
            this.PaymentRequest = new HashSet<PaymentRequest>();
        }
    
        public int ID { get; set; }
        public int ContractMonthID { get; set; }
        public decimal Value { get; set; }
        public Nullable<int> SkuId { get; set; }
        public Nullable<decimal> SkuQuantity { get; set; }
        public bool IsReassigned { get; set; }
        public Nullable<System.DateTime> LastChangeDateTime { get; set; }
        public Nullable<int> LastChangeUserID { get; set; }
    
        public virtual ContractMonth ContractMonth { get; set; }
        public virtual Sku Sku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequest { get; set; }
    }
}
