//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequestSectionMap
    {
        [Key, Column(Order=0)]
        public int PaymentRequestStatusID { get; set; }
        [Key, Column(Order=1)]
        public int RoleID { get; set; }
        [Key, Column(Order=2)]
        public int PaymentRequestSectionID { get; set; }
    
        public virtual PaymentRequestSection PaymentRequestSection { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus { get; set; }
        public virtual Role Role { get; set; }
    }
}
