//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequestStatusHistory
    {
        public int ID { get; set; }
        public int PaymentRequestID { get; set; }
        public Nullable<int> StatusIDOld { get; set; }
        public int StatusIDNew { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreationUserID { get; set; }
        public string Comment { get; set; }
    
        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus1 { get; set; }
        public virtual User User { get; set; }
    }
}
