//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionUserExpand
    {
        public int RegionID { get; set; }
        public Nullable<int> ParentRegionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleCode { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
