//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionExpand
    {
        public int RegionID { get; set; }
        public int ParentRegionID { get; set; }
        public int Lvl { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
