//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionRoleUserManagerExpand
    {
        public int RegionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ManagerRegionID { get; set; }
        public Nullable<int> ManagerRoleID { get; set; }
        public string ManagerRoleCode { get; set; }
        public Nullable<int> ManagerUserID { get; set; }
        public int Lvl { get; set; }
    }
}
