//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionRoleManager
    {
        public int RegionID { get; set; }
        public int RoleID { get; set; }
        public string RoleCode { get; set; }
        public int RegionToRoleID { get; set; }
        public int ManagerRegionID { get; set; }
        public int ManagerRoleID { get; set; }
        public string ManagerRoleCode { get; set; }
        public int ManagerRegionToRoleID { get; set; }
    }
}
