//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.RegionToRole = new HashSet<RegionToRole>();
            this.ContractRoleVisibility = new HashSet<ContractRoleVisibility>();
            this.RoleExpand = new HashSet<RoleExpand>();
            this.RoleExpand1 = new HashSet<RoleExpand>();
            this.Role1 = new HashSet<Role>();
            this.ContractStatusActionMap = new HashSet<ContractStatusActionMap>();
            this.PaymentRequestStatusActionMap = new HashSet<PaymentRequestStatusActionMap>();
            this.PaymentRequestSectionMap = new HashSet<PaymentRequestSectionMap>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Ident { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string IsStrictHierarchy { get; set; }
        public bool IsDeleted { get; set; }
        public bool AllowLoginToWebInterface { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionToRole> RegionToRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoleVisibility> ContractRoleVisibility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleExpand> RoleExpand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleExpand> RoleExpand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role1 { get; set; }
        public virtual Role Role2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractStatusActionMap> ContractStatusActionMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestStatusActionMap> PaymentRequestStatusActionMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestSectionMap> PaymentRequestSectionMap { get; set; }
    }
}
