//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePointFact
    {
        [Key, Column(Order=0), ForeignKey("SalePoint")]
        public int SalePointID { get; set; }
        public int AverageSkuCount { get; set; }
        public decimal DoorsCountOfHeinekenFridge { get; set; }
        public int AverageTopSkuCount { get; set; }
        public bool HasVisits { get; set; }
    
        public virtual SalePoint SalePoint { get; set; }
    }
}
