//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalePoint()
        {
            this.Contractor = new HashSet<Contractor>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> SalePointSegmentID { get; set; }
        public int SalePointChannelID { get; set; }
        public int RegionID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int DistributorID { get; set; }
        public Nullable<int> TradeNetID { get; set; }
        public bool IsIncludedToRoute { get; set; }
        public Nullable<decimal> InvestmentPercent { get; set; }
        public Nullable<int> JeansID { get; set; }
        public Nullable<int> OriginalID { get; set; }
        public string ContactFullName { get; set; }
        public string ContactPhoneMobile { get; set; }
        public string ContactPhoneStationary { get; set; }
        public Nullable<decimal> DoorsCountOfInBevFridge { get; set; }
        public Nullable<decimal> DoorsCountOfEfesSabFridge { get; set; }
        public Nullable<decimal> DoorsCountOfHeinekenFridge { get; set; }
        public Nullable<decimal> DoorsCountOfBalticaFridge { get; set; }
        public Nullable<decimal> DoorsCountOfOthersFridge { get; set; }
        public string CityName { get; set; }
        public string DoorsCountNotBranding { get; set; }
        public int SalePointStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contractor> Contractor { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Region Region { get; set; }
        public virtual SalePointSegment SalePointSegment { get; set; }
        public virtual SalePointChannel SalePointChannel { get; set; }
        public virtual TradeNet TradeNet { get; set; }
        public virtual SalePointFact SalePointFact { get; set; }
    }
}
