//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOut
    {
        public int ID { get; set; }
        public int ContractorID { get; set; }
        public int MonthID { get; set; }
        public Nullable<decimal> ValueFact { get; set; }
        public Nullable<decimal> ValuePlan { get; set; }
        public string Comment { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Month Month { get; set; }
    }
}
