//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeNetToDistributorReagionAsmBinding
    {
        public int DistributorRegionAsmID { get; set; }
        public int TradeNetID { get; set; }
        public System.DateTime LastChangeDateTime { get; set; }
    
        public virtual DistributorToRegionAsmBinding DistributorToRegionAsmBinding { get; set; }
        public virtual TradeNet TradeNet { get; set; }
    }
}
