//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tim.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Version()
        {
            this.Budget = new HashSet<Budget>();
            this.BudgetData = new HashSet<BudgetData>();
            this.ImportFileBudget = new HashSet<ImportFileBudget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime ActualDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<int> ActualYear { get; set; }
        public Nullable<int> ActualMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetData> BudgetData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportFileBudget> ImportFileBudget { get; set; }
        public virtual Month Month { get; set; }
    }
}
